// Mapa nombre-de-farmaco (normalizado) -> id de ficha. Generado por cima_scrape.py.
window.DRUG_ALIAS = {
    "solucion salina fisiologica":  "salina_fisiologica",
    "adrenalina":  "adrenalina",
    "amiodarona":  "amiodarona",
    "lidocaina":  "lidocaina",
    "bicarbonato sodico 1 m":  "bicarbonato_sodico",
    "naloxona":  "naloxona",
    "atropina":  "atropina",
    "dobutamina":  "dobutamina",
    "dopamina":  "dopamina",
    "glucosa":  "glucosa",
    "solucion glucosalina":  "glucosalina",
    "ringer lactato":  "ringer_lactato",
    "noradrenalina":  "noradrenalina",
    "paracetamol":  "paracetamol",
    "metamizol magnesico":  "metamizol_magnesico",
    "tramadol":  "tramadol",
    "morfina":  "morfina",
    "fentanilo":  "fentanilo",
    "dexclorfeniramina":  "dexclorfeniramina",
    "famotidina":  "famotidina",
    "metilprednisolona":  "metilprednisolona",
    "enalapril":  "enalapril",
    "captopril":  "captopril",
    "candesartan":  "candesartan",
    "valsartan":  "valsartan",
    "losartan":  "losartan",
    "espironolactona":  "espironolactona",
    "eplerenona":  "eplerenona",
    "furosemida":  "furosemida",
    "hidroclorotiazida":  "hidroclorotiazida",
    "carvedilol":  "carvedilol",
    "bisoprolol":  "bisoprolol",
    "digoxina":  "digoxina",
    "ivabradina":  "ivabradina",
    "sacubitril valsartan":  "sacubitril_valsartan",
    "dapagliflozina":  "dapagliflozina",
    "empagliflozina":  "empagliflozina",
    "bemiparina":  "bemiparina",
    "tolvaptan":  "tolvaptan",
    "nitroglicerina":  "nitroglicerina",
    "levosimendan":  "levosimendan",
    "midazolam":  "midazolam",
    "adenosina":  "adenosina",
    "lorazepam":  "lorazepam",
    "propranolol":  "propranolol",
    "metoprolol":  "metoprolol",
    "verapamilo":  "verapamilo",
    "diltiazem":  "diltiazem",
    "flecainida":  "flecainida",
    "propafenona":  "propafenona",
    "dronedarona":  "dronedarona",
    "enoxaparina hbpm":  "enoxaparina",
    "apixaban":  "apixaban",
    "dabigatran":  "dabigatran",
    "edoxaban":  "edoxaban",
    "rivaroxaban":  "rivaroxaban",
    "acenocumarol":  "acenocumarol",
    "acido acetilsalicilico":  "acido_acetilsalicilico",
    "ibuprofeno":  "ibuprofeno",
    "meperidina":  "meperidina",
    "nitroglicerina sublingual comprimido":  "nitroglicerina",
    "nitroglicerina sublingual espray":  "nitroglicerina",
    "nitroglicerina intravenosa":  "nitroglicerina",
    "metoprolol oral":  "metoprolol",
    "atenolol oral":  "atenolol",
    "metoprolol intravenoso":  "metoprolol",
    "amlodipino":  "amlodipino",
    "ticagrelor":  "ticagrelor",
    "prasugrel":  "prasugrel",
    "clopidogrel":  "clopidogrel",
    "tirofiban":  "tirofiban",
    "heparina sodica":  "heparina_sodica",
    "fondaparinux":  "fondaparinux",
    "enoxaparina":  "enoxaparina",
    "tenecteplasa":  "tenecteplasa",
    "alteplasa rtpa":  "alteplasa",
    "reteplasa":  "reteplasa",
    "atorvastatina":  "atorvastatina",
    "rosuvastatina":  "rosuvastatina",
    "ramipril":  "ramipril",
    "irbesartan":  "irbesartan",
    "labetalol":  "labetalol",
    "esmolol":  "esmolol",
    "omeprazol":  "omeprazol",
    "prednisona":  "prednisona",
    "colchicina":  "colchicina",
    "glucosa 5":  "glucosa",
    "heparina de bajo peso molecular":  "heparina_bajo_peso",
    "cloxacilina":  "cloxacilina",
    "ampicilina":  "ampicilina",
    "gentamicina":  "gentamicina",
    "ceftriaxona":  "ceftriaxona",
    "daptomicina":  "daptomicina",
    "fosfomicina":  "fosfomicina",
    "meropenem":  "meropenem",
    "ceftazidima":  "ceftazidima",
    "piperacilina tazobactam":  "piperacilina_tazobactam",
    "amoxicilina":  "amoxicilina",
    "clindamicina":  "clindamicina",
    "claritromicina":  "claritromicina",
    "clortalidona":  "clortalidona",
    "atenolol":  "atenolol",
    "suero glucosado 5":  "suero_glucosado",
    "urapidil":  "urapidil",
    "dexketoprofeno trometamol":  "dexketoprofeno_trometamol",
    "tinzaparina":  "tinzaparina",
    "pentoxifilina":  "pentoxifilina",
    "naproxeno":  "naproxeno",
    "heparina sodica topica gel o pomada con 1 000 ui":  "heparina_sodica",
    "pentoxifilina grageas de 400 mg o comprimidos de liberacion prolongada de 600 mg":  "pentoxifilina",
    "diclofenaco":  "diclofenaco",
    "diclofenaco gel":  "diclofenaco",
    "enoxaparina hbpm en dosis terapeuticas":  "enoxaparina",
    "amoxicilina acido clavulanico":  "amoxicilina_acido_clavulanico",
    "azitromicina":  "azitromicina",
    "levofloxacino":  "levofloxacino",
    "ciprofloxacino":  "ciprofloxacino",
    "acido tranexamico":  "acido_tranexamico",
    "vitamina k":  "vitamina_k",
    "heparina sodica hnf":  "heparina_sodica",
    "dalteparina":  "dalteparina",
    "nadroparina":  "nadroparina",
    "oxigeno":  "oxigeno",
    "solucion glucosada al 5":  "glucosada",
    "salbutamol nebulizado":  "salbutamol",
    "salbutamol inhalado":  "salbutamol",
    "hidrocortisona":  "hidrocortisona",
    "budesonida nebulizada":  "budesonida",
    "salmeterol fluticasona":  "salmeterol",
    "formoterol budesonida":  "formoterol",
    "formoterol beclometasona":  "formoterol",
    "formoterol fluticasona":  "formoterol",
    "salbutamol":  "salbutamol",
    "salmeterol":  "salmeterol",
    "formoterol":  "formoterol",
    "moxifloxacino":  "moxifloxacino",
    "cefotaxima":  "cefotaxima",
    "cefepima":  "cefepima",
    "tobramicina":  "tobramicina",
    "amikacina":  "amikacina",
    "vancomicina":  "vancomicina",
    "linezolid":  "linezolid",
    "ceftarolina":  "ceftarolina",
    "ertapenem":  "ertapenem",
    "oseltamivir":  "oseltamivir",
    "imipenem":  "imipenem",
    "metoclopramida":  "metoclopramida",
    "baclofeno":  "baclofeno",
    "gabapentina":  "gabapentina",
    "metronidazol":  "metronidazol",
    "fluconazol":  "fluconazol",
    "itraconazol":  "itraconazol",
    "voriconazol":  "voriconazol",
    "aciclovir":  "aciclovir",
    "famciclovir":  "famciclovir",
    "valaciclovir":  "valaciclovir",
    "ganciclovir":  "ganciclovir",
    "foscarnet":  "foscarnet",
    "cidofovir":  "cidofovir",
    "fluticasona":  "fluticasona",
    "budesonida":  "budesonida",
    "pantoprazol":  "pantoprazol",
    "eritromicina":  "eritromicina",
    "esomeprazol":  "esomeprazol",
    "terlipresina":  "terlipresina",
    "somatostatina":  "somatostatina",
    "plasma leucodeplecionado":  "plasma_leucodeplecionado",
    "lactulosa":  "lactulosa",
    "omeprazol o pantoprazol o esomeprazol claritromicina amoxicilina metronidazol":  "omeprazol",
    "clindamicina tobramicina ampicilina":  "clindamicina",
    "metronidazol tobramicina ampicilina":  "metronidazol",
    "cefepima tobramicina":  "cefepima",
    "meropenem linezolid o daptomicina o vancomicina":  "meropenem",
    "amoxicilina clavulanico ciprofloxacino o cefixima":  "amoxicilina_clavulanico",
    "ertapenem piperacilina tazobactam":  "ertapenem",
    "glucosa al 10":  "glucosa",
    "morfina o fentanilo opiaceos parenterales":  "morfina",
    "ondansetron":  "ondansetron",
    "droperidol":  "droperidol",
    "loperamida":  "loperamida",
    "doxiciclina":  "doxiciclina",
    "cefixima":  "cefixima",
    "calcio colecalciferol":  "calcio",
    "solucion salina fisiologica alternando con glucosado 5":  "salina_fisiologica_alternando",
    "octreotida":  "octreotida",
    "dexametasona":  "dexametasona",
    "suero fisiologico solucion salina al 0 9":  "suero_fisiologico",
    "ceftazidima avibactam metronidazol ampicilina":  "ceftazidima_avibactam",
    "glucosa 10 alternando con suero salino fisiologico":  "glucosa",
    "flumazenilo":  "flumazenilo",
    "lactulosa enema":  "lactulosa",
    "amilorida hidroclorotiazida":  "amilorida",
    "albumina humana 20":  "albumina_humana",
    "norfloxacino":  "norfloxacino",
    "macrogol":  "macrogol",
    "diosmina":  "diosmina",
    "cefuroxima":  "cefuroxima",
    "nitroglicerina rectal":  "nitroglicerina",
    "diltiazem topico al 2":  "diltiazem",
    "dexketoprofeno":  "dexketoprofeno",
    "domperidona":  "domperidona",
    "diazepam":  "diazepam",
    "sumatriptan":  "sumatriptan",
    "zolmitriptan":  "zolmitriptan",
    "rizatriptan":  "rizatriptan",
    "almotriptan":  "almotriptan",
    "eletriptan":  "eletriptan",
    "naratriptan":  "naratriptan",
    "suero glucosalino o fisiologico":  "suero_glucosalino",
    "valproato sodico":  "valproato_sodico",
    "topiramato":  "topiramato",
    "zonisamida":  "zonisamida",
    "acido valproico":  "acido_valproico",
    "carbamazepina":  "carbamazepina",
    "oxcarbazepina":  "oxcarbazepina",
    "eslicarbazepina":  "eslicarbazepina",
    "pregabalina":  "pregabalina",
    "amitriptilina":  "amitriptilina",
    "sulpirida":  "sulpirida",
    "betahistina":  "betahistina",
    "dimenhidrinato":  "dimenhidrinato",
    "glucosa hipertonica al 50":  "glucosa_hipertonica",
    "glucosa hipertonica":  "glucosa_hipertonica",
    "levetiracetam":  "levetiracetam",
    "lacosamida":  "lacosamida",
    "vitamina b1 tiamina":  "vitamina_b",
    "haloperidol":  "haloperidol",
    "icatibant":  "icatibant",
    "citicolina":  "citicolina",
    "nimodipino":  "nimodipino",
    "simvastatina":  "simvastatina",
    "solucion glucosalina o salina fisiologica":  "glucosalina",
    "ampicilina cefotaxima vancomicina":  "ampicilina",
    "meropenem gentamicina":  "meropenem",
    "cefotaxima o ceftriaxona vancomicina":  "cefotaxima",
    "meropenem o moxifloxacino vancomicina":  "meropenem",
    "cefotaxima o ceftriaxona ampicilina vancomicina":  "cefotaxima",
    "vancomicina meropenem o moxifloxacino trimetoprima sulfametoxazol":  "vancomicina",
    "ceftazidima o cefepima ampicilina vancomicina":  "ceftazidima",
    "vancomicina cefepima o ceftazidima o meropenem":  "vancomicina",
    "cefotaxima vancomicina":  "cefotaxima",
    "vancomicina ceftazidima amikacina":  "vancomicina",
    "pirazinamida":  "pirazinamida",
    "ceftazidima vancomicina":  "ceftazidima",
    "clonazepam":  "clonazepam",
    "inmunoglobulina humana":  "inmunoglobulina_humana",
    "clorazepato dipotasico":  "clorazepato_dipotasico",
    "quetiapina":  "quetiapina",
    "olanzapina":  "olanzapina",
    "risperidona":  "risperidona",
    "ziprasidona":  "ziprasidona",
    "lorazepam haloperidol":  "lorazepam",
    "midazolam haloperidol":  "midazolam",
    "olanzapina midazolam":  "olanzapina",
    "alprazolam":  "alprazolam",
    "escitalopram":  "escitalopram",
    "fluoxetina":  "fluoxetina",
    "sertralina":  "sertralina",
    "duloxetina":  "duloxetina",
    "venlafaxina":  "venlafaxina",
    "metformina":  "metformina",
    "glimepirida":  "glimepirida",
    "gliclazida mr":  "gliclazida_mr",
    "repaglinida":  "repaglinida",
    "sitagliptina":  "sitagliptina",
    "liraglutida":  "liraglutida",
    "acarbosa":  "acarbosa",
    "suero glucosado 5 o 10":  "suero_glucosado",
    "glucosa pura oral":  "glucosa_pura",
    "solucion glucosada al 10":  "glucosada",
    "solucion salina seminormal 0 45":  "salina_seminormal",
    "solucion salina fisiologica 0 9":  "salina_fisiologica",
    "solucion salina fisiologica ssf 0 9":  "salina_fisiologica",
    "levotiroxina sodica":  "levotiroxina_sodica",
    "solucion salina fisiologica alternando con suero glucosado 5":  "salina_fisiologica_alternando",
    "fludrocortisona":  "fludrocortisona",
    "amilorida":  "amilorida",
    "suero oral":  "suero",
    "solucion salina hipertonica al 3 preparada diluyendo 60 ml de clna al 20 en 400 ml de ssf":  "salina_hipertonica",
    "solucion salina hipertonica al 3":  "salina_hipertonica",
    "solucion salina hipotonica al 0 45":  "salina_hipotonica",
    "solucion salina fisiologica al 0 9":  "salina_fisiologica",
    "desmopresina":  "desmopresina",
    "carbonato calcico":  "carbonato_calcico",
    "colecalciferol":  "colecalciferol",
    "acido zoledronico":  "acido_zoledronico",
    "pamidronato disodico":  "pamidronato_disodico",
    "calcitonina":  "calcitonina",
    "calcifediol":  "calcifediol",
    "cinacalcet":  "cinacalcet",
    "fosfato nm dihidrogeno fosfato de sodio monohidrato":  "fosfato_nm",
    "fosfato monosodico 1m preferible o monopotasico":  "fosfato_monosodico",
    "fosfato monosodico 1m fresenius kabi 120 mg ml":  "fosfato_monosodico",
    "fosfato monosodico o monopotasico iv":  "fosfato_monosodico",
    "fosfato iv":  "fosfato",
    "furosemida u otros diureticos de asa":  "furosemida_u_otros",
    "ezetimiba":  "ezetimiba",
    "albumina humana":  "albumina_humana",
    "nifedipino":  "nifedipino",
    "agua ingesta hidrica oral":  "agua",
    "alfuzosina":  "alfuzosina",
    "tamsulosina":  "tamsulosina",
    "mepivacaina":  "mepivacaina",
    "fosfomicina trometamol":  "fosfomicina_trometamol",
    "paracetamol tramadol":  "paracetamol",
    "dexketoprofeno tramadol":  "dexketoprofeno",
    "ceftazidima avibactam":  "ceftazidima_avibactam",
    "ofloxacino":  "ofloxacino",
    "anestesia local":  "anestesia_local",
    "fenilefrina":  "fenilefrina",
    "finasterida":  "finasterida",
    "dutasterida":  "dutasterida",
    "tadalafilo":  "tadalafilo",
    "albumina humana al 20":  "albumina_humana",
    "albumina humana al 5":  "albumina_humana",
    "teicoplanina":  "teicoplanina",
    "sulfadiazina":  "sulfadiazina",
    "micafungina":  "micafungina",
    "anidulafungina":  "anidulafungina",
    "caspofungina":  "caspofungina",
    "carbon activado":  "carbon_activado",
    "inmunoglobulina botulinica humana":  "inmunoglobulina_botulinica_humana",
    "inmunoglobulina antitetanica":  "inmunoglobulina_antitetanica",
    "propofol":  "propofol",
    "cisatracurio":  "cisatracurio",
    "inmunoglobulina antirrabica":  "inmunoglobulina_antirrabica",
    "vacuna antirrabica virus inactivado":  "vacuna_antirrabica",
    "ribavirina":  "ribavirina",
    "ceftriaxona azitromicina":  "ceftriaxona",
    "cefixima azitromicina":  "cefixima",
    "paracetamol o aine":  "paracetamol",
    "dextrometorfano":  "dextrometorfano",
    "acetilcisteina":  "acetilcisteina",
    "heparina de bajo peso molecular hbpm":  "heparina_bajo_peso",
    "ceftriaxona amoxicilina acido clavulanico azitromicina":  "ceftriaxona",
    "tocilizumab":  "tocilizumab",
    "ruxolitinib":  "ruxolitinib",
    "calcifediol vitamina d":  "calcifediol",
    "tenofovir emtricitabina":  "tenofovir",
    "zidovudina lamivudina":  "zidovudina",
    "raltegravir":  "raltegravir",
    "atazanavir ritonavir":  "atazanavir",
    "darunavir ritonavir":  "darunavir",
    "cefazolina":  "cefazolina",
    "alopurinol":  "alopurinol",
    "febuxostat":  "febuxostat",
    "betametasona":  "betametasona",
    "deflazacort":  "deflazacort",
    "inmunoglobulina intravenosa":  "inmunoglobulina",
    "ciclofosfamida":  "ciclofosfamida",
    "buprenorfina":  "buprenorfina",
    "oxicodona":  "oxicodona",
    "tapentadol":  "tapentadol",
    "paroxetina":  "paroxetina",
    "hidroxizina":  "hidroxizina",
    "granisetron":  "granisetron",
    "mesna 2 mercapto etano sulfonato de sodio":  "mesna",
    "acido folico":  "acido_folico",
    "carbon activado dosis repetidas":  "carbon_activado",
    "jarabe de ipecacuana":  "jarabe_ipecacuana",
    "apomorfina":  "apomorfina",
    "solucion glucosada al 5 bicarbonato sodico 1 6 m":  "glucosada",
    "bicarbonato sodico 1 6 m":  "bicarbonato_sodico",
    "solucion glucosada al 5 cloruro potasico":  "glucosada",
    "solucion salina fisiologica cloruro potasico":  "salina_fisiologica",
    "carbon activado sorbitol":  "carbon_activado",
    "verapamilo o diltiazem":  "verapamilo",
    "oxigeno mascarilla venturi":  "oxigeno",
    "neostigmina":  "neostigmina",
    "milrinona":  "milrinona",
    "suero fisiologico solucion salina 0 9":  "suero_fisiologico",
    "agua o solucion salina fisiologica lavado cutaneo y ocular":  "agua",
    "tiosulfato sodico":  "tiosulfato_sodico",
    "carbon activado dosis unica":  "carbon_activado",
    "carbon activado dosis multiples":  "carbon_activado",
    "glucosado 5":  "glucosado",
    "rocuronio":  "rocuronio",
    "solucion glucosada 5 cloruro potasico":  "glucosada",
    "naloxona en infusion continua":  "naloxona_infusion",
    "efedrina":  "efedrina",
    "silibinina":  "silibinina",
    "vitamina c acido ascorbico":  "vitamina_c",
    "plasma fresco congelado":  "plasma_fresco_congelado",
    "dmsa acido dimercaptosuccinico":  "dmsa",
    "bicarbonato sodico 1 m glucosada 5":  "bicarbonato_sodico",
    "adrenalina o noradrenalina":  "adrenalina",
    "tiosulfato sodico al 25":  "tiosulfato_sodico",
    "folinato calcico leucovorina calcica":  "folinato_calcico",
    "inmunoglobulina f ab 2 frente a v ammodytes":  "inmunoglobulina_f",
    "glucosa hipertonica 50":  "glucosa_hipertonica",
    "gabapentina pregabalina oxcarbazepina topiramato zonisamida":  "gabapentina",
    "solucion glucosada 5 alternando con suero salino fisiologico":  "glucosada",
    "bromazepam":  "bromazepam",
    "solucion salina fisiologica clna 0 9":  "salina_fisiologica",
    "solucion glucosalina cloruro potasico":  "glucosalina",
    "etomidato":  "etomidato",
    "moxifloxacino colirio":  "moxifloxacino",
    "ofloxacino colirio":  "ofloxacino",
    "calcio comprimidos efervescentes 500 mg":  "calcio",
    "tetracaina oxibuprocaina colirio":  "tetracaina",
    "fluoresceina colirio al 2":  "fluoresceina",
    "almagato":  "almagato",
    "suero oral sobres con electrolitos":  "suero",
    "solucion glucosada al 5 o solucion salina fisiologica":  "glucosada",
    "solucion salina fisiologica alternando con glucosalina":  "salina_fisiologica_alternando",
    "solucion glucosada al 5 o solucion glucosalina calentada a 40 42 c":  "glucosada",
    "ropivacaina":  "ropivacaina",
    "iloprost":  "iloprost",
    "nifedipino liberacion prolongada":  "nifedipino",
    "sildenafilo":  "sildenafilo",
    "bicarbonato sodico":  "bicarbonato_sodico",
    "glucosa al 5":  "glucosa",
    "metoclopramida ibuprofeno":  "metoclopramida",
    "ciprofloxacino topico otico":  "ciprofloxacino_otico",
    "ciprofloxacino oral":  "ciprofloxacino",
    "oximetazolina":  "oximetazolina",
    "azelastina":  "azelastina",
    "ambroxol":  "ambroxol",
    "norfloxacino colirio al 0 3":  "norfloxacino",
    "mometasona":  "mometasona",
    "loratadina":  "loratadina",
    "desloratadina":  "desloratadina",
    "cefadroxilo":  "cefadroxilo",
    "ketoprofeno":  "ketoprofeno",
    "carmelosa colirio lubricante ocular":  "carmelosa",
    "ciprofloxacino colirio 0 3":  "ciprofloxacino",
    "moxifloxacino colirio 0 5":  "moxifloxacino",
    "aciclovir pomada oftalmica 3":  "aciclovir",
    "diclofenaco colirio 0 1":  "diclofenaco",
    "dexametasona colirio 0 1":  "dexametasona",
    "ketotifeno":  "ketotifeno",
    "acido fusidico":  "acido_fusidico",
    "carmelosa":  "carmelosa",
    "butilescopolamina":  "butilescopolamina",
    "ampicilina sulbactam":  "ampicilina_sulbactam",
    "complejo protrombinico":  "complejo_protrombinico",
    "fenitoina sodica":  "fenitoina_sodica",
    "tetracaina oxibuprocaina":  "tetracaina",
    "fluoresceina oxibuprocaina":  "fluoresceina",
    "lidocaina al 2 sin adrenalina":  "lidocaina",
    "ringer lactato o solucion salina fisiologica":  "ringer_lactato",
    "adrenalina en infusion continua":  "adrenalina_infusion",
    "cetirizina":  "cetirizina",
    "mupirocina":  "mupirocina",
    "aciclovir topico":  "aciclovir",
    "brivudina":  "brivudina",
    "clotrimazol":  "clotrimazol",
    "permetrina":  "permetrina",
    "metilprednisolona topica":  "metilprednisolona",
    "ebastina":  "ebastina",
    "clindamicina topica":  "clindamicina",
    "clindamicina oral":  "clindamicina",
    "metamizol":  "metamizol",
    "cefuroxima axetilo":  "cefuroxima_axetilo",
    "adrenalina nebulizada":  "adrenalina",
    "salbutamol inhalado mdi con camara espaciadora":  "salbutamol",
    "prednisona oral":  "prednisona",
    "salbutamol nebulizado continuo":  "salbutamol_continuo",
    "ranitidina":  "ranitidina",
    "solucion salina fisiologica mas dextrosa al 3 5":  "salina_fisiologica_mas",
    "solucion glucosalina 1 2":  "glucosalina",
    "solucion glucosalina 1 3":  "glucosalina",
    "solucion glucosalina 1 5":  "glucosalina",
    "cefotaxima o ceftriaxona":  "cefotaxima",
    "vitamina a":  "vitamina",
    "lidocaina viscosa 2":  "lidocaina_viscosa",
    "diazepam rectal":  "diazepam",
    "midazolam bucal":  "midazolam_bucal",
    "diazepam iv":  "diazepam",
    "midazolam iv":  "midazolam",
    "metamizol sodico":  "metamizol_sodico",
    "cefoxitina":  "cefoxitina",
    "lamotrigina":  "lamotrigina",
    "cloperastina":  "cloperastina",
    "macrogol 4000":  "macrogol",
    "doxilamina piridoxina":  "doxilamina",
    "suero glucosado al 10":  "suero_glucosado",
    "difenhidramina":  "difenhidramina",
    "metoclopramida hidroxizina":  "metoclopramida",
    "atosiban":  "atosiban",
    "metotrexato":  "metotrexato",
    "metronidazol gel":  "metronidazol",
    "clindamicina crema vaginal":  "clindamicina_vaginal",
    "clindamicina ovulos vaginales":  "clindamicina_ovulos_vaginales",
    "clotrimazol crema vaginal":  "clotrimazol_vaginal",
    "clotrimazol comprimido vaginal":  "clotrimazol_vaginal",
    "clotrimazol ovulo vaginal":  "clotrimazol_ovulo_vaginal",
    "aciclovir iv":  "aciclovir",
    "clorhexidina ovulos vaginales":  "clorhexidina_ovulos_vaginales",
    "estradiol ovulos vaginales":  "estradiol_ovulos_vaginales",
    "estradiol anillo vaginal":  "estradiol_anillo_vaginal",
    "albumina":  "albumina",
    "levonorgestrel":  "levonorgestrel",
    "agua intravenosa":  "agua",
    "solucion glucosada al 20":  "glucosada",
    "solucion glucosada al 40":  "glucosada",
    "solucion salina fisiologica cloruro sodico 0 9":  "salina_fisiologica",
    "solucion salina al 2":  "salina",
    "solucion salina al 7 5":  "salina",
    "solucion salina al 0 45 hipotonica":  "salina",
    "sugammadex":  "sugammadex",
    "adrenalina adultos via endotraqueal":  "adrenalina",
    "adrenalina ninos via endotraqueal":  "adrenalina",
    "adrenalina neonatos via endotraqueal":  "adrenalina",
    "solucion salina fisiologica o ringer lactato":  "salina_fisiologica",
    "acetazolamida":  "acetazolamida",
    "hierro carboximaltosa":  "hierro_carboximaltosa",
    "isoproterenol":  "isoproterenol",
    "vernakalant":  "vernakalant",
    "procainamida":  "procainamida",
    "indometacina":  "indometacina",
    "clonidina":  "clonidina",
    "hidralazina":  "hidralazina",
    "sulodexida capsulas de 15 y 30 mg":  "sulodexida",
    "terbutalina inhalada":  "terbutalina",
    "tiotropio":  "tiotropio",
    "umeclidinio":  "umeclidinio",
    "aclidinio":  "aclidinio",
    "indacaterol":  "indacaterol",
    "olodaterol":  "olodaterol",
    "cefditoreno":  "cefditoreno",
    "aztreonam":  "aztreonam",
    "clorpromazina":  "clorpromazina",
    "hioscina":  "hioscina",
    "glucagon":  "glucagon",
    "idarucizumab":  "idarucizumab",
    "lactitol":  "lactitol",
    "hemina":  "hemina",
    "racecadotrilo":  "racecadotrilo",
    "rifaximina":  "rifaximina",
    "fidaxomicina":  "fidaxomicina",
    "saccharomyces boulardii":  "saccharomyces_boulardii",
    "mesalazina":  "mesalazina",
    "beclometasona":  "beclometasona",
    "infliximab":  "infliximab",
    "ciclosporina":  "ciclosporina",
    "adalimumab":  "adalimumab",
    "hidrosmina":  "hidrosmina",
    "frovatriptan":  "frovatriptan",
    "flunarizina":  "flunarizina",
    "erenumab":  "erenumab",
    "galcanezumab":  "galcanezumab",
    "fremanezumab":  "fremanezumab",
    "piracetam":  "piracetam",
    "tiamina":  "tiamina",
    "tiopental sodico":  "tiopental_sodico",
    "difenilhidantoina fenitoina":  "difenilhidantoina",
    "nicardipino":  "nicardipino",
    "rifampicina":  "rifampicina",
    "isoniazida":  "isoniazida",
    "estreptomicina":  "estreptomicina",
    "amantadina":  "amantadina",
    "piridostigmina":  "piridostigmina",
    "bromocriptina":  "bromocriptina",
    "dantroleno":  "dantroleno",
    "levomepromazina":  "levomepromazina",
    "insulina asparta lispro glulisina analogo ultrarrapido":  "insulina_asparta",
    "insulina soluble neutra humana regular":  "insulina_soluble_neutra",
    "nateglinida":  "nateglinida",
    "insulina subcutanea basal bolo correccion":  "insulina",
    "insulina accion rapida":  "insulina",
    "insulina subcutanea pauta basal bolo correccion":  "insulina",
    "tiamazol o carbimazol":  "tiamazol",
    "patiromer":  "patiromer",
    "lactato de magnesio":  "lactato_magnesio",
    "calcitriol":  "calcitriol",
    "fenoximetilpenicilina":  "fenoximetilpenicilina",
    "nitrofurantoina":  "nitrofurantoina",
    "flavoxato":  "flavoxato",
    "etilefrina":  "etilefrina",
    "fenilpropanolamina":  "fenilpropanolamina",
    "etilefrina oral":  "etilefrina",
    "insulina":  "insulina",
    "pirimetamina":  "pirimetamina",
    "polietilenglicol macrogol":  "polietilenglicol",
    "zanamivir":  "zanamivir",
    "podofilotoxina":  "podofilotoxina",
    "nirmatrelvir ritonavir":  "nirmatrelvir",
    "remdesivir":  "remdesivir",
    "casirivimab imdevimab":  "casirivimab",
    "sotrovimab":  "sotrovimab",
    "anakinra":  "anakinra",
    "baricitinib":  "baricitinib",
    "siltuximab":  "siltuximab",
    "sarilumab":  "sarilumab",
    "dolutegravir":  "dolutegravir",
    "tizanidina":  "tizanidina",
    "metocarbamol":  "metocarbamol",
    "nitroprusiato":  "nitroprusiato",
    "rituximab":  "rituximab",
    "filgrastim":  "filgrastim",
    "lenograstim":  "lenograstim",
    "nistatina":  "nistatina",
    "rasburicasa":  "rasburicasa",
    "ferroglicina sulfato":  "ferroglicina_sulfato",
    "hierro sacarosa":  "hierro_sacarosa",
    "cianocobalamina hidroxicobalamina":  "cianocobalamina",
    "polietilenglicol":  "polietilenglicol",
    "polietilenglicol irrigacion intestinal total":  "polietilenglicol",
    "hidroxicobalamina":  "hidroxicobalamina",
    "ciproheptadina":  "ciproheptadina",
    "colestiramina":  "colestiramina",
    "nalmefeno":  "nalmefeno",
    "deferoxamina":  "deferoxamina",
    "fitomenadiona vitamina k":  "fitomenadiona",
    "tiamina vitamina b1":  "tiamina",
    "clometiazol":  "clometiazol",
    "tiaprida":  "tiaprida",
    "ketamina":  "ketamina",
    "conestat alfa":  "conestat_alfa",
    "espiramicina":  "espiramicina",
    "ciclopentolato colirio 1":  "ciclopentolato",
    "levocabastina":  "levocabastina",
    "triamcinolona":  "triamcinolona",
    "bencilpenicilina":  "bencilpenicilina",
    "ciclopentolato":  "ciclopentolato",
    "miconazol":  "miconazol",
    "xilometazolina":  "xilometazolina",
    "teofilina":  "teofilina",
    "difenilhidantoina":  "difenilhidantoina",
    "tiopental":  "tiopental",
    "cefaclor":  "cefaclor",
    "cleboprida":  "cleboprida",
    "clobazam":  "clobazam",
    "mebendazol":  "mebendazol",
    "misoprostol":  "misoprostol",
    "promestrieno crema":  "promestrieno",
    "megestrol menestral":  "megestrol",
    "noretisterona acetato":  "noretisterona_acetato",
    "norepinefrina":  "norepinefrina",
    "succinilcolina":  "succinilcolina",
    "fenobarbital":  "fenobarbital"
};
